version: '3.8'

services:

  #app:
  # image: dev-and-talent
  #ports:
  # - 3000:3000
  db:
    container_name: db_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: talenteddev
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dev_talent_db
    ports:
      - "5432:5432"
