version: '3.8'

services:

  app:
    image: dev-and-talent
    ports:
      - 3000:3000
  db:
    container_name: db_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dev_talent_db
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pg_admin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pepe@pepe.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
     - "5050:80"
